services:
  app:
    container_name: clean-arch-app
    build:
      context: .
      dockerfile: dockerfile.fpm
    volumes:
      - ./:/var/www
    networks:
      - clean-arch

  nginx:
    container_name: clean-arch-nginx
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - clean-arch

  postgres:
    container_name: clean-arch-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-clean-arch}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clean-arch

networks:
  clean-arch:
    driver: bridge
